CREATE TABLE master_produk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nama_produk VARCHAR(255),
    harga       DECIMAL,
    kategori    VARCHAR(255),
    stok        INTEGER,
    CONSTRAINT pk_masterproduk PRIMARY KEY (id)
);